### ISSUE TITLE
Wiki not up to date with 07a1dfe

### ISSUE THREAD

**Issue by Raffarti** [riccardodebenedictis/oRatio#17]
Hello,
https://github.com/pstlab/oRatio/wiki/From-PDDL-to-timelines still refers to `IntervalPredicate` and `ImpulsivePredicate`. (07a1dfe)

EDIT: also https://github.com/pstlab/oRatio/wiki/Representing-Timelines

**Comment by riccardodebenedictis** [comment]
Wiki updated!
thanks for spotting the issue
