### ISSUE TITLE
Tau issue?

### ISSUE THREAD

**Issue by Raffarti** [riccardodebenedictis/oRatio#19]
I just noticed that
```
class Rover {
    real id;
    
    Rover(real id) :
        id(id) {}
    
    predicate Equipped() {false;}
}

Rover r0 = new Rover(0.0);
Rover r1 = new Rover(1.0);

fact e = new r1.Equipped();
goal t = new r0.Equipped();
```
actually finds a solution.
Defining `Rover` as `Rover : StateVariable` doesn't find a solution (unless r1 is used for the goal as well), which looks more natural.

**Comment by riccardodebenedictis** [comment]
Thank you for spotting this!
I was using `this` within rule definition, but it clearly makes no sense.. I replaced `this` with `tau` and I solved this issue!
